/** Advanced help without a translation retains its English source. */
export const FRENCH_UI: Readonly<Record<string, string>> = {
  'More holiday options': 'Autres options du voyage',
  'Holiday options': 'Options du voyage',
  Account: 'Compte',
  'Your account': 'Votre compte',
  'Account activity': 'Activité du compte',
  'Account JSON': 'Compte au format JSON',
  'Account history CSV': 'Historique du compte au format CSV',
  'Account history JSON': 'Historique du compte au format JSON',
  Balances: 'Soldes',
  Receipts: 'Reçus',
  'Holiday sections': 'Rubriques du voyage',
  'Save notification preferences':
    'Enregistrer les préférences de notification',
  'Signed-in browsers': 'Navigateurs connectés',
  'Verify your email': 'Vérifier votre adresse e-mail',
  'Send verification email': 'Envoyer l’e-mail de vérification',
  'Confirm your email address for account recovery.':
    'Confirmez votre adresse e-mail pour récupérer votre compte.',
  'Holiday updates': 'Actualités du voyage',
  'Expenses and payments involving me': 'Dépenses et paiements me concernant',
  'No holiday updates': 'Aucune actualité du voyage',
  'Delete your account': 'Supprimer votre compte',
  Expenses: 'Dépenses',
  Travellers: 'Voyageurs',
  'Settle up': 'Régler les comptes',
  History: 'Historique',
  Activity: 'Activité',
  'New holiday': 'Nouveau voyage',
  'Import holiday': 'Importer un voyage',
  'Archived holidays': 'Voyages archivés',
  'Import a holiday': 'Importer un voyage',
  'Import file': 'Fichier à importer',
  Holiday: 'Voyage',
  'Choose your traveller': 'Choisissez votre voyageur',
  'Which traveller are you?': 'Quel voyageur êtes-vous ?',
  'Add expense': 'Ajouter une dépense',
  'Add a receipt': 'Ajouter un reçu',
  'Add item': 'Ajouter un article',
  'Add another': 'En ajouter une autre',
  Add: 'Ajouter',
  'Add payment details': 'Ajouter les coordonnées de paiement',
  'Add any useful details': 'Ajoutez les détails utiles',
  'Add the first expense': 'Ajouter la première dépense',
  'Add a shared expense or start with a receipt.':
    'Ajoutez une dépense partagée ou commencez par un reçu.',
  Save: 'Enregistrer',
  'Save changes': 'Enregistrer les modifications',
  'Save pending changes': 'Enregistrer les modifications en attente',
  Cancel: 'Annuler',
  Close: 'Fermer',
  Delete: 'Supprimer',
  Remove: 'Retirer',
  Edit: 'Modifier',
  Discard: 'Abandonner',
  Restore: 'Restaurer',
  'Download JSON': 'Télécharger le JSON',
  Download: 'Télécharger',
  Retry: 'Réessayer',
  'Retry refresh': 'Actualiser à nouveau',
  Continue: 'Continuer',
  Back: 'Retour',
  Done: 'Terminé',
  Undo: 'Annuler l’action',
  Repeat: 'Répéter',
  Share: 'Partager',
  Print: 'Imprimer',
  Name: 'Nom',
  Email: 'E-mail',
  'Email address': 'Adresse e-mail',
  Password: 'Mot de passe',
  'Current password': 'Mot de passe actuel',
  'New password': 'Nouveau mot de passe',
  'Display name': 'Nom affiché',
  'Sign in': 'Se connecter',
  'Sign out': 'Se déconnecter',
  'Create account': 'Créer un compte',
  'Forgot password?': 'Mot de passe oublié ?',
  'Send reset link': 'Envoyer le lien de réinitialisation',
  'Back to sign in': 'Revenir à la connexion',
  'Reset password': 'Réinitialiser le mot de passe',
  'Confirm email': 'Confirmer l’e-mail',
  'Verify email': 'Vérifier l’e-mail',
  'Email verification': 'Vérification de l’e-mail',
  'Browser sessions': 'Sessions du navigateur',
  'Sign out other browsers': 'Déconnecter les autres navigateurs',
  'Delete account': 'Supprimer le compte',
  'Delete my account': 'Supprimer mon compte',
  'Type your email to confirm': 'Saisissez votre e-mail pour confirmer',
  Date: 'Date',
  Time: 'Heure',
  'Time zone': 'Fuseau horaire',
  Amount: 'Montant',
  'Amount (': 'Montant (',
  Currency: 'Devise',
  'Paid by': 'Payé par',
  'Shared by': 'Partagé par',
  Payer: 'Personne qui a payé',
  Participants: 'Participants',
  Traveller: 'Voyageur',
  Category: 'Catégorie',
  Sort: 'Trier',
  Anyone: 'Tout le monde',
  All: 'Tous',
  'All categories': 'Toutes les catégories',
  'All currencies': 'Toutes les devises',
  'All holiday activity': 'Toute l’activité du voyage',
  'From date': 'À partir du',
  'To date': 'Jusqu’au',
  'Needs review only': 'À vérifier uniquement',
  'Search expenses': 'Rechercher des dépenses',
  'Find expenses': 'Trouver des dépenses',
  'Search names, items or places': 'Rechercher des noms, articles ou lieux',
  Filter: 'Filtrer',
  'Clear filters': 'Effacer les filtres',
  'Spending breakdown': 'Répartition des dépenses',
  'Break down spending by': 'Répartir les dépenses par',
  'Spending by category': 'Dépenses par catégorie',
  'Spending by day': 'Dépenses par jour',
  'Each traveller’s share': 'Part de chaque voyageur',
  Day: 'Jour',
  'By day': 'Par jour',
  'By item': 'Par article',
  Food: 'Repas',
  Drinks: 'Boissons',
  Transport: 'Transport',
  Stays: 'Hébergement',
  Activities: 'Activités',
  Shopping: 'Achats',
  'Health & family': 'Santé et famille',
  Other: 'Autres',
  'Needs review': 'À vérifier',
  'No expenses yet': 'Aucune dépense pour le moment',
  'No matching expenses': 'Aucune dépense correspondante',
  'No amounts to show yet': 'Aucun montant à afficher',
  'Recently added': 'Ajoutées récemment',
  'Newest first': 'Les plus récentes d’abord',
  'Oldest first': 'Les plus anciennes d’abord',
  'Highest amount': 'Montant le plus élevé',
  'Lowest amount': 'Montant le plus bas',
  'A fair share of the good times.': 'De bons moments, des comptes équitables.',
  'Every trip starts together.': 'Chaque voyage commence ensemble.',
  'Scan receipt': 'Scanner un reçu',
  'Scan receipt photo': 'Scanner une photo de reçu',
  'Upload receipt': 'Importer un reçu',
  'Upload photo': 'Importer une photo',
  'Receipt photo': 'Photo du reçu',
  'Receipt photo (optional)': 'Photo du reçu (facultatif)',
  Receipt: 'Reçu',
  'Receipt details': 'Détails du reçu',
  'Receipt chat': 'Discussion sur le reçu',
  'Item chat': 'Discussion sur l’article',
  'Receipt currency': 'Devise du reçu',
  'Receipt total': 'Total du reçu',
  'Original amount': 'Montant d’origine',
  'Actual bank charge': 'Montant réellement débité',
  'Exchange rate': 'Taux de change',
  'Manual rate': 'Taux de change manuel',
  'Check rate': 'Vérifier le taux',
  'Check & save': 'Vérifier et enregistrer',
  'Check &amp; save': 'Vérifier et enregistrer',
  'Confirm & save expense': 'Confirmer et enregistrer la dépense',
  'Confirm &amp; save expense': 'Confirmer et enregistrer la dépense',
  'Details & split': 'Détails et répartition',
  'Back to details & split': 'Revenir aux détails et à la répartition',
  Split: 'Répartition',
  Equal: 'À parts égales',
  Percentages: 'Pourcentages',
  Units: 'Unités',
  Quantity: 'Quantité',
  Item: 'Article',
  'Item name': 'Nom de l’article',
  Price: 'Prix',
  Subtotal: 'Sous-total',
  Tax: 'Taxe',
  Tip: 'Pourboire',
  Discount: 'Remise',
  Total: 'Total',
  Notes: 'Notes',
  Note: 'Note',
  Location: 'Lieu',
  Place: 'Lieu',
  Optional: 'Facultatif',
  '(optional)': '(facultatif)',
  'Remove receipt photo': 'Retirer la photo du reçu',
  'Choose an icon': 'Choisir une icône',
  Icon: 'Icône',
  Automatic: 'Automatique',
  'Automatic detection': 'Détection automatique',
  Check: 'Vérifier',
  Payment: 'Paiement',
  Payments: 'Paiements',
  'Record paid': 'Enregistrer le paiement',
  'Record payment': 'Enregistrer un paiement',
  From: 'De',
  To: 'À',
  Method: 'Mode de paiement',
  Reference: 'Référence',
  'Payment details': 'Coordonnées de paiement',
  'Bank details (optional)': 'Coordonnées bancaires (facultatif)',
  'Bank details:': 'Coordonnées bancaires :',
  'Bank transfer, cash…': 'Virement, espèces…',
  'Copy amount and reference': 'Copier le montant et la référence',
  Remind: 'Envoyer un rappel',
  'All square': 'Tout est réglé',
  Balance: 'Solde',
  'Before this payment:': 'Avant ce paiement :',
  'Suggested transfers': 'Virements suggérés',
  'Paid upfront': 'Avancé',
  'Cost share': 'Part des dépenses',
  'Holiday details': 'Détails du voyage',
  'Holiday name': 'Nom du voyage',
  'Settlement currency': 'Devise de règlement',
  'Start date': 'Date de début',
  'End date': 'Date de fin',
  Budget: 'Budget',
  'Holiday budget': 'Budget du voyage',
  'Group budget': 'Budget du groupe',
  'Budget used': 'Budget utilisé',
  Remaining: 'Restant',
  'Spent so far': 'Dépenses à ce jour',
  'Daily average': 'Moyenne quotidienne',
  'Trip summary': 'Bilan du voyage',
  'Holiday summary': 'Bilan du voyage',
  'End-of-trip summary': 'Bilan de fin de voyage',
  'Average per traveller': 'Moyenne par voyageur',
  'Final transfers': 'Virements finaux',
  'Archive for me': 'Archiver pour moi',
  'Leave holiday': 'Quitter le voyage',
  'Transfer ownership': 'Transférer la propriété',
  'Choose a connected traveller': 'Choisir un voyageur avec un compte',
  'Delete holiday': 'Supprimer le voyage',
  'Manage holiday': 'Gérer le voyage',
  'Holiday management': 'Gestion du voyage',
  'Restore holiday': 'Restaurer le voyage',
  'Joined on': 'Arrivé le',
  'Left on': 'Parti le',
  'Counts as': 'Compte pour',
  'Traveller options': 'Options du voyageur',
  'Remove traveller': 'Retirer le voyageur',
  Invite: 'Inviter',
  'Invite traveller': 'Inviter un voyageur',
  'Active invitations': 'Invitations actives',
  'Invite link': 'Lien d’invitation',
  'Copy link': 'Copier le lien',
  Copied: 'Copié',
  'Offline expense capture': 'Saisir des dépenses hors ligne',
  'Enable on this device': 'Activer sur cet appareil',
  'Disable on this device': 'Désactiver sur cet appareil',
  'Open capture form': 'Ouvrir le formulaire de saisie',
  'Sync pending expenses': 'Synchroniser les dépenses en attente',
  'Review pending entries': 'Vérifier les éléments en attente',
  'Review holiday': 'Voir le voyage',
  'Edit pending': 'Modifier l’élément en attente',
  'Edit pending expense': 'Modifier la dépense en attente',
  'Keep receipt photo': 'Conserver la photo du reçu',
  'I checked the converted amount.': 'J’ai vérifié le montant converti.',
  'A photo was shared with TripTab': 'Une photo a été partagée avec TripTab',
  'Attach to this holiday': 'Joindre à ce voyage',
  'Discard photo': 'Supprimer la photo',
  'Notification preferences': 'Préférences de notification',
  Notifications: 'Notifications',
  'Browser notifications': 'Notifications du navigateur',
  'Allow settlement reminders': 'Autoriser les rappels de paiement',
  'Only expenses I’m involved in': 'Uniquement les dépenses me concernant',
  'Daily summary': 'Résumé quotidien',
  'As activity happens': 'Au fil des événements',
  'In-app only': 'Dans l’application uniquement',
  'No notifications': 'Aucune notification',
  'Save preferences': 'Enregistrer les préférences',
  'Current browser': 'Ce navigateur',
  Revoke: 'Révoquer',
  'Sign out this browser': 'Déconnecter ce navigateur',
  'Repeat expense': 'Répéter une dépense',
  'REPEAT EXPENSE': 'RÉPÉTER UNE DÉPENSE',
  'How long': 'Pendant combien de temps',
  'Until a date': 'Jusqu’à une date',
  'A number of times': 'Un nombre de fois',
  'Last date': 'Dernière date',
  'Number of copies': 'Nombre de copies',
  Every: 'Tous les',
  day: 'jour',
  '2 days': '2 jours',
  week: 'semaine',
  'A NEW ADVENTURE': 'UNE NOUVELLE AVENTURE',
  'HOLIDAY LEDGER': 'COMPTES DU VOYAGE',
  'Your expenses': 'Vos dépenses',
  'About TripTab': 'À propos de TripTab',
  Help: 'Aide',
  Settings: 'Paramètres',
  General: 'Général',
  Language: 'Langue',
  'Interface language': 'Langue de l’interface',
  English: 'Anglais',
  Spanish: 'Espagnol',
  Appearance: 'Apparence',
  Dark: 'Sombre',
  Light: 'Clair',
  System: 'Système',
  'Before:': 'Avant :',
  'After:': 'Après :',
  'Changed by': 'Modifié par',
  Changes: 'Modifications',
  'Restore from history': 'Restaurer depuis l’historique',
  'Data export': 'Export des données',
  'Export holiday': 'Exporter le voyage',
  'Financial CSV': 'Données financières en CSV',
  'Download CSV': 'Télécharger le CSV',
  'Download receipt': 'Télécharger le reçu',
  'View photo': 'Voir la photo',
  'Show more': 'Afficher plus',
  'Show less': 'Afficher moins',
  'Show details': 'Afficher les détails',
  'Hide details': 'Masquer les détails',
  Expand: 'Développer',
  Collapse: 'Réduire',
  'Check it. Split it.': 'Vérifiez. Répartissez.',
  'A shared dinner doesn’t have to mean an equal bill.':
    'Un dîner partagé ne signifie pas forcément partager l’addition à parts égales.',
  'ChatGPT connected': 'ChatGPT connecté',
  'ChatGPT plan': 'Abonnement ChatGPT',
  'Connect ChatGPT': 'Connecter ChatGPT',
  'Disconnect ChatGPT': 'Déconnecter ChatGPT',
  'Add notes first': 'Ajouter d’abord des notes',
  'Ask your assistant to itemise it':
    'Demandez à votre assistant de détailler les articles',
  Processing: 'Traitement en cours',
  Saved: 'Enregistré',
  Manual: 'Manuel',
  Search: 'Rechercher',
  Send: 'Envoyer',
  Reply: 'Répondre',
  Replies: 'Réponses',
  Details: 'Détails',
  Change: 'Modifier',
  'Change reference': 'Modifier la référence',
  Allocated: 'Réparti',
  'Your share': 'Votre part',
  People: 'Personnes',
};
