/** Advanced help without a translation retains its English source. */
export const GERMAN_UI: Readonly<Record<string, string>> = {
  'More holiday options': 'Weitere Reiseoptionen',
  'Holiday options': 'Reiseoptionen',
  Account: 'Konto',
  'Your account': 'Dein Konto',
  'Account activity': 'Kontoaktivität',
  'Account JSON': 'Konto als JSON',
  'Account history CSV': 'Kontoverlauf als CSV',
  'Account history JSON': 'Kontoverlauf als JSON',
  Balances: 'Salden',
  Receipts: 'Belege',
  'Holiday sections': 'Reisebereiche',
  'Save notification preferences': 'Benachrichtigungseinstellungen speichern',
  'Signed-in browsers': 'Angemeldete Browser',
  'Verify your email': 'E-Mail-Adresse bestätigen',
  'Send verification email': 'Bestätigungs-E-Mail senden',
  'Confirm your email address for account recovery.':
    'Bestätige deine E-Mail-Adresse zur Kontowiederherstellung.',
  'Holiday updates': 'Reiseaktualisierungen',
  'Expenses and payments involving me':
    'Ausgaben und Zahlungen mit meiner Beteiligung',
  'No holiday updates': 'Keine Reiseaktualisierungen',
  'Delete your account': 'Dein Konto löschen',
  Expenses: 'Ausgaben',
  Travellers: 'Reisende',
  'Settle up': 'Abrechnen',
  History: 'Verlauf',
  Activity: 'Aktivität',
  'New holiday': 'Neue Reise',
  'Import holiday': 'Reise importieren',
  'Archived holidays': 'Archivierte Reisen',
  'Import a holiday': 'Eine Reise importieren',
  'Import file': 'Importdatei',
  Holiday: 'Reise',
  'Choose your traveller': 'Wähle deinen Reisenden',
  'Which traveller are you?': 'Welcher Reisende bist du?',
  'Add expense': 'Ausgabe hinzufügen',
  'Add a receipt': 'Beleg hinzufügen',
  'Add item': 'Position hinzufügen',
  'Add another': 'Weitere hinzufügen',
  Add: 'Hinzufügen',
  'Add payment details': 'Zahlungsdaten hinzufügen',
  'Add any useful details': 'Hilfreiche Angaben hinzufügen',
  'Add the first expense': 'Erste Ausgabe hinzufügen',
  'Add a shared expense or start with a receipt.':
    'Füge eine gemeinsame Ausgabe hinzu oder beginne mit einem Beleg.',
  Save: 'Speichern',
  'Save changes': 'Änderungen speichern',
  'Save pending changes': 'Ausstehende Änderungen speichern',
  Cancel: 'Abbrechen',
  Close: 'Schließen',
  Delete: 'Löschen',
  Remove: 'Entfernen',
  Edit: 'Bearbeiten',
  Discard: 'Verwerfen',
  Restore: 'Wiederherstellen',
  'Download JSON': 'JSON herunterladen',
  Download: 'Herunterladen',
  Retry: 'Erneut versuchen',
  'Retry refresh': 'Erneut aktualisieren',
  Continue: 'Weiter',
  Back: 'Zurück',
  Done: 'Fertig',
  Undo: 'Rückgängig',
  Repeat: 'Wiederholen',
  Share: 'Teilen',
  Print: 'Drucken',
  Name: 'Name',
  Email: 'E-Mail',
  'Email address': 'E-Mail-Adresse',
  Password: 'Passwort',
  'Current password': 'Aktuelles Passwort',
  'New password': 'Neues Passwort',
  'Display name': 'Anzeigename',
  'Sign in': 'Anmelden',
  'Sign out': 'Abmelden',
  'Create account': 'Konto erstellen',
  'Forgot password?': 'Passwort vergessen?',
  'Send reset link': 'Link zum Zurücksetzen senden',
  'Back to sign in': 'Zur Anmeldung zurück',
  'Reset password': 'Passwort zurücksetzen',
  'Confirm email': 'E-Mail bestätigen',
  'Verify email': 'E-Mail bestätigen',
  'Email verification': 'E-Mail-Bestätigung',
  'Browser sessions': 'Browsersitzungen',
  'Sign out other browsers': 'Andere Browser abmelden',
  'Delete account': 'Konto löschen',
  'Delete my account': 'Mein Konto löschen',
  'Type your email to confirm': 'Gib zur Bestätigung deine E-Mail-Adresse ein',
  Date: 'Datum',
  Time: 'Uhrzeit',
  'Time zone': 'Zeitzone',
  Amount: 'Betrag',
  'Amount (': 'Betrag (',
  Currency: 'Währung',
  'Paid by': 'Bezahlt von',
  'Shared by': 'Geteilt von',
  Payer: 'Zahlende Person',
  Participants: 'Beteiligte',
  Traveller: 'Reisender',
  Category: 'Kategorie',
  Sort: 'Sortieren',
  Anyone: 'Alle',
  All: 'Alle',
  'All categories': 'Alle Kategorien',
  'All currencies': 'Alle Währungen',
  'All holiday activity': 'Alle Reiseaktivitäten',
  'From date': 'Ab Datum',
  'To date': 'Bis Datum',
  'Needs review only': 'Nur zu prüfen',
  'Search expenses': 'Ausgaben suchen',
  'Find expenses': 'Ausgaben finden',
  'Search names, items or places': 'Namen, Positionen oder Orte suchen',
  Filter: 'Filtern',
  'Clear filters': 'Filter löschen',
  'Spending breakdown': 'Ausgabenübersicht',
  'Break down spending by': 'Ausgaben aufschlüsseln nach',
  'Spending by category': 'Ausgaben nach Kategorie',
  'Spending by day': 'Ausgaben nach Tag',
  'Each traveller’s share': 'Anteil jedes Reisenden',
  Day: 'Tag',
  'By day': 'Nach Tag',
  'By item': 'Nach Position',
  Food: 'Essen',
  Drinks: 'Getränke',
  Transport: 'Verkehr',
  Stays: 'Unterkünfte',
  Activities: 'Aktivitäten',
  Shopping: 'Einkäufe',
  'Health & family': 'Gesundheit und Familie',
  Other: 'Sonstiges',
  'Needs review': 'Zu prüfen',
  'No expenses yet': 'Noch keine Ausgaben',
  'No matching expenses': 'Keine passenden Ausgaben',
  'No amounts to show yet': 'Noch keine Beträge vorhanden',
  'Recently added': 'Zuletzt hinzugefügt',
  'Newest first': 'Neueste zuerst',
  'Oldest first': 'Älteste zuerst',
  'Highest amount': 'Höchster Betrag',
  'Lowest amount': 'Niedrigster Betrag',
  'A fair share of the good times.': 'Schöne Zeiten, fair geteilte Kosten.',
  'Every trip starts together.': 'Jede Reise beginnt gemeinsam.',
  'Scan receipt': 'Beleg scannen',
  'Scan receipt photo': 'Belegfoto scannen',
  'Upload receipt': 'Beleg hochladen',
  'Upload photo': 'Foto hochladen',
  'Receipt photo': 'Belegfoto',
  'Receipt photo (optional)': 'Belegfoto (optional)',
  Receipt: 'Beleg',
  'Receipt details': 'Belegdetails',
  'Receipt chat': 'Belegchat',
  'Item chat': 'Chat zur Position',
  'Receipt currency': 'Belegwährung',
  'Receipt total': 'Belegsumme',
  'Original amount': 'Originalbetrag',
  'Actual bank charge': 'Tatsächlich abgebuchter Betrag',
  'Exchange rate': 'Wechselkurs',
  'Manual rate': 'Manueller Wechselkurs',
  'Check rate': 'Wechselkurs prüfen',
  'Check & save': 'Prüfen und speichern',
  'Check &amp; save': 'Prüfen und speichern',
  'Confirm & save expense': 'Ausgabe bestätigen und speichern',
  'Confirm &amp; save expense': 'Ausgabe bestätigen und speichern',
  'Details & split': 'Details und Aufteilung',
  'Back to details & split': 'Zurück zu Details und Aufteilung',
  Split: 'Aufteilung',
  Equal: 'Gleichmäßig',
  Percentages: 'Prozentanteile',
  Units: 'Einheiten',
  Quantity: 'Menge',
  Item: 'Position',
  'Item name': 'Positionsname',
  Price: 'Preis',
  Subtotal: 'Zwischensumme',
  Tax: 'Steuer',
  Tip: 'Trinkgeld',
  Discount: 'Rabatt',
  Total: 'Gesamt',
  Notes: 'Notizen',
  Note: 'Notiz',
  Location: 'Ort',
  Place: 'Ort',
  Optional: 'Optional',
  '(optional)': '(optional)',
  'Remove receipt photo': 'Belegfoto entfernen',
  'Choose an icon': 'Symbol auswählen',
  Icon: 'Symbol',
  Automatic: 'Automatisch',
  'Automatic detection': 'Automatische Erkennung',
  Check: 'Prüfen',
  Payment: 'Zahlung',
  Payments: 'Zahlungen',
  'Record paid': 'Als bezahlt erfassen',
  'Record payment': 'Zahlung erfassen',
  From: 'Von',
  To: 'An',
  Method: 'Zahlungsart',
  Reference: 'Verwendungszweck',
  'Payment details': 'Zahlungsdaten',
  'Bank details (optional)': 'Bankverbindung (optional)',
  'Bank details:': 'Bankverbindung:',
  'Bank transfer, cash…': 'Überweisung, Bargeld…',
  'Copy amount and reference': 'Betrag und Verwendungszweck kopieren',
  Remind: 'Erinnern',
  'All square': 'Alles ausgeglichen',
  Balance: 'Saldo',
  'Before this payment:': 'Vor dieser Zahlung:',
  'Suggested transfers': 'Vorgeschlagene Überweisungen',
  'Paid upfront': 'Vorgestreckt',
  'Cost share': 'Kostenanteil',
  'Holiday details': 'Reisedetails',
  'Holiday name': 'Reisename',
  'Settlement currency': 'Abrechnungswährung',
  'Start date': 'Startdatum',
  'End date': 'Enddatum',
  Budget: 'Budget',
  'Holiday budget': 'Reisebudget',
  'Group budget': 'Gruppenbudget',
  'Budget used': 'Verbrauchtes Budget',
  Remaining: 'Übrig',
  'Spent so far': 'Bisher ausgegeben',
  'Daily average': 'Tagesdurchschnitt',
  'Trip summary': 'Reiseübersicht',
  'Holiday summary': 'Reiseübersicht',
  'End-of-trip summary': 'Abschlussübersicht',
  'Average per traveller': 'Durchschnitt pro Reisendem',
  'Final transfers': 'Abschließende Überweisungen',
  'Archive for me': 'Für mich archivieren',
  'Leave holiday': 'Reise verlassen',
  'Transfer ownership': 'Eigentümerschaft übertragen',
  'Choose a connected traveller': 'Reisenden mit Konto auswählen',
  'Delete holiday': 'Reise löschen',
  'Manage holiday': 'Reise verwalten',
  'Holiday management': 'Reiseverwaltung',
  'Restore holiday': 'Reise wiederherstellen',
  'Joined on': 'Dabei seit',
  'Left on': 'Abgereist am',
  'Counts as': 'Zählt als',
  'Traveller options': 'Optionen für Reisende',
  'Remove traveller': 'Reisenden entfernen',
  Invite: 'Einladen',
  'Invite traveller': 'Reisenden einladen',
  'Active invitations': 'Aktive Einladungen',
  'Invite link': 'Einladungslink',
  'Copy link': 'Link kopieren',
  Copied: 'Kopiert',
  'Offline expense capture': 'Ausgaben offline erfassen',
  'Enable on this device': 'Auf diesem Gerät aktivieren',
  'Disable on this device': 'Auf diesem Gerät deaktivieren',
  'Open capture form': 'Erfassungsformular öffnen',
  'Sync pending expenses': 'Ausstehende Ausgaben synchronisieren',
  'Review pending entries': 'Ausstehende Einträge prüfen',
  'Review holiday': 'Reise prüfen',
  'Edit pending': 'Ausstehenden Eintrag bearbeiten',
  'Edit pending expense': 'Ausstehende Ausgabe bearbeiten',
  'Keep receipt photo': 'Belegfoto behalten',
  'I checked the converted amount.':
    'Ich habe den umgerechneten Betrag geprüft.',
  'A photo was shared with TripTab': 'Ein Foto wurde mit TripTab geteilt',
  'Attach to this holiday': 'Dieser Reise hinzufügen',
  'Discard photo': 'Foto verwerfen',
  'Notification preferences': 'Benachrichtigungseinstellungen',
  Notifications: 'Benachrichtigungen',
  'Browser notifications': 'Browserbenachrichtigungen',
  'Allow settlement reminders': 'Zahlungserinnerungen erlauben',
  'Only expenses I’m involved in': 'Nur Ausgaben mit meiner Beteiligung',
  'Daily summary': 'Tägliche Zusammenfassung',
  'As activity happens': 'Bei neuen Aktivitäten',
  'In-app only': 'Nur in der App',
  'No notifications': 'Keine Benachrichtigungen',
  'Save preferences': 'Einstellungen speichern',
  'Current browser': 'Dieser Browser',
  Revoke: 'Widerrufen',
  'Sign out this browser': 'Diesen Browser abmelden',
  'Repeat expense': 'Ausgabe wiederholen',
  'REPEAT EXPENSE': 'AUSGABE WIEDERHOLEN',
  'How long': 'Wie lange',
  'Until a date': 'Bis zu einem Datum',
  'A number of times': 'Eine bestimmte Anzahl',
  'Last date': 'Letztes Datum',
  'Number of copies': 'Anzahl der Kopien',
  Every: 'Alle',
  day: 'Tag',
  '2 days': '2 Tage',
  week: 'Woche',
  'A NEW ADVENTURE': 'EIN NEUES ABENTEUER',
  'HOLIDAY LEDGER': 'REISEABRECHNUNG',
  'Your expenses': 'Deine Ausgaben',
  'About TripTab': 'Über TripTab',
  Help: 'Hilfe',
  Settings: 'Einstellungen',
  General: 'Allgemein',
  Language: 'Sprache',
  'Interface language': 'Sprache der Oberfläche',
  English: 'Englisch',
  Spanish: 'Spanisch',
  Appearance: 'Darstellung',
  Dark: 'Dunkel',
  Light: 'Hell',
  System: 'System',
  'Before:': 'Vorher:',
  'After:': 'Nachher:',
  'Changed by': 'Geändert von',
  Changes: 'Änderungen',
  'Restore from history': 'Aus dem Verlauf wiederherstellen',
  'Data export': 'Datenexport',
  'Export holiday': 'Reise exportieren',
  'Financial CSV': 'Finanzdaten als CSV',
  'Download CSV': 'CSV herunterladen',
  'Download receipt': 'Beleg herunterladen',
  'View photo': 'Foto ansehen',
  'Show more': 'Mehr anzeigen',
  'Show less': 'Weniger anzeigen',
  'Show details': 'Details anzeigen',
  'Hide details': 'Details ausblenden',
  Expand: 'Ausklappen',
  Collapse: 'Einklappen',
  'Check it. Split it.': 'Prüfen. Aufteilen.',
  'A shared dinner doesn’t have to mean an equal bill.':
    'Ein gemeinsames Abendessen muss keine gleiche Aufteilung der Rechnung bedeuten.',
  'ChatGPT connected': 'ChatGPT verbunden',
  'ChatGPT plan': 'ChatGPT-Tarif',
  'Connect ChatGPT': 'ChatGPT verbinden',
  'Disconnect ChatGPT': 'ChatGPT trennen',
  'Add notes first': 'Zuerst Notizen hinzufügen',
  'Ask your assistant to itemise it':
    'Bitte deinen Assistenten, die Positionen aufzuschlüsseln',
  Processing: 'Wird verarbeitet',
  Saved: 'Gespeichert',
  Manual: 'Manuell',
  Search: 'Suchen',
  Send: 'Senden',
  Reply: 'Antworten',
  Replies: 'Antworten',
  Details: 'Details',
  Change: 'Ändern',
  'Change reference': 'Verwendungszweck ändern',
  Allocated: 'Zugeordnet',
  'Your share': 'Dein Anteil',
  People: 'Personen',
};
