/** Untranslated advanced help uses the English source text. */
export const SPANISH_UI: Readonly<Record<string, string>> = {
  'More holiday options': 'Más opciones del viaje',
  'Holiday options': 'Opciones del viaje',
  Account: 'Cuenta',
  'Your account': 'Tu cuenta',
  'Account activity': 'Actividad de la cuenta',
  'Account JSON': 'JSON de la cuenta',
  'Account history CSV': 'Historial de la cuenta en CSV',
  'Account history JSON': 'Historial de la cuenta en JSON',
  Balances: 'Saldos',
  Receipts: 'Recibos',
  'Holiday sections': 'Secciones del viaje',
  'Save notification preferences': 'Guardar preferencias de notificación',
  'Signed-in browsers': 'Navegadores con sesión iniciada',
  'Verify your email': 'Verifica tu correo',
  'Send verification email': 'Enviar correo de verificación',
  'Confirm your email address for account recovery.':
    'Confirma tu correo para recuperar la cuenta.',
  'Holiday updates': 'Actualizaciones del viaje',
  'Expenses and payments involving me': 'Gastos y pagos en los que participo',
  'No holiday updates': 'Sin actualizaciones del viaje',
  'Delete your account': 'Eliminar tu cuenta',
  Expenses: 'Gastos',
  Travellers: 'Viajeros',
  'Settle up': 'Liquidar cuentas',
  History: 'Historial',
  Activity: 'Actividad',
  'New holiday': 'Nuevo viaje',
  'Import holiday': 'Importar viaje',
  'Archived holidays': 'Viajes archivados',
  'Import a holiday': 'Importar un viaje',
  'Import file': 'Archivo para importar',
  Holiday: 'Viaje',
  'Choose your traveller': 'Elige tu viajero',
  'Which traveller are you?': '¿Qué viajero eres?',
  'Add expense': 'Añadir gasto',
  'Add a receipt': 'Añadir un recibo',
  'Add item': 'Añadir artículo',
  'Add another': 'Añadir otro',
  Add: 'Añadir',
  'Add payment details': 'Añadir datos de pago',
  'Add any useful details': 'Añade los detalles que puedan ayudar',
  'Add the first expense': 'Añadir el primer gasto',
  'Add a shared expense or start with a receipt.':
    'Añade un gasto compartido o empieza con un recibo.',
  Save: 'Guardar',
  'Save changes': 'Guardar cambios',
  'Save pending changes': 'Guardar cambios pendientes',
  Cancel: 'Cancelar',
  Close: 'Cerrar',
  Delete: 'Eliminar',
  Remove: 'Quitar',
  Edit: 'Editar',
  Discard: 'Descartar',
  Restore: 'Restaurar',
  'Download JSON': 'Descargar JSON',
  Download: 'Descargar',
  Retry: 'Reintentar',
  'Retry refresh': 'Actualizar de nuevo',
  Continue: 'Continuar',
  Back: 'Volver',
  Done: 'Listo',
  Undo: 'Deshacer',
  Repeat: 'Repetir',
  Share: 'Compartir',
  Print: 'Imprimir',
  Name: 'Nombre',
  Email: 'Correo electrónico',
  'Email address': 'Correo electrónico',
  Password: 'Contraseña',
  'Current password': 'Contraseña actual',
  'New password': 'Nueva contraseña',
  'Display name': 'Nombre para mostrar',
  'Sign in': 'Iniciar sesión',
  'Sign out': 'Cerrar sesión',
  'Create account': 'Crear cuenta',
  'Forgot password?': '¿Olvidaste tu contraseña?',
  'Send reset link': 'Enviar enlace de recuperación',
  'Back to sign in': 'Volver al inicio de sesión',
  'Reset password': 'Restablecer contraseña',
  'Confirm email': 'Confirmar correo',
  'Verify email': 'Verificar correo',
  'Email verification': 'Verificación del correo',
  'Browser sessions': 'Sesiones del navegador',
  'Sign out other browsers': 'Cerrar las demás sesiones',
  'Delete account': 'Eliminar cuenta',
  'Delete my account': 'Eliminar mi cuenta',
  'Type your email to confirm': 'Escribe tu correo para confirmar',
  Date: 'Fecha',
  Time: 'Hora',
  'Time zone': 'Zona horaria',
  Amount: 'Importe',
  'Amount (': 'Importe (',
  Currency: 'Moneda',
  'Paid by': 'Pagado por',
  'Shared by': 'Compartido por',
  Payer: 'Persona que pagó',
  Participants: 'Participantes',
  Traveller: 'Viajero',
  Category: 'Categoría',
  Sort: 'Ordenar',
  Anyone: 'Cualquiera',
  All: 'Todos',
  'All categories': 'Todas las categorías',
  'All currencies': 'Todas las monedas',
  'All holiday activity': 'Toda la actividad del viaje',
  'From date': 'Desde',
  'To date': 'Hasta',
  'Needs review only': 'Solo pendientes de revisión',
  'Search expenses': 'Buscar gastos',
  'Find expenses': 'Buscar gastos',
  'Search names, items or places': 'Buscar nombres, artículos o lugares',
  Filter: 'Filtrar',
  'Clear filters': 'Quitar filtros',
  'Spending breakdown': 'Desglose de gastos',
  'Break down spending by': 'Desglosar gastos por',
  'Spending by category': 'Gastos por categoría',
  'Spending by day': 'Gastos por día',
  'Each traveller’s share': 'Parte de cada viajero',
  Day: 'Día',
  'By day': 'Por día',
  'By item': 'Por artículo',
  Food: 'Comida',
  Drinks: 'Bebidas',
  Transport: 'Transporte',
  Stays: 'Alojamiento',
  Activities: 'Actividades',
  Shopping: 'Compras',
  'Health & family': 'Salud y familia',
  Other: 'Otros',
  'Needs review': 'Pendiente de revisión',
  'No expenses yet': 'Todavía no hay gastos',
  'No matching expenses': 'No hay gastos que coincidan',
  'No amounts to show yet': 'Todavía no hay importes que mostrar',
  'Recently added': 'Añadidos recientemente',
  'Newest first': 'Más recientes primero',
  'Oldest first': 'Más antiguos primero',
  'Highest amount': 'Mayor importe',
  'Lowest amount': 'Menor importe',
  'A fair share of the good times.': 'Buenos momentos, cuentas justas.',
  'Every trip starts together.': 'Todo viaje empieza juntos.',
  'Scan receipt': 'Escanear recibo',
  'Scan receipt photo': 'Escanear foto del recibo',
  'Upload receipt': 'Subir recibo',
  'Upload photo': 'Subir foto',
  'Receipt photo': 'Foto del recibo',
  'Receipt photo (optional)': 'Foto del recibo (opcional)',
  Receipt: 'Recibo',
  'Receipt details': 'Detalles del recibo',
  'Receipt chat': 'Chat del recibo',
  'Item chat': 'Chat del artículo',
  'Receipt currency': 'Moneda del recibo',
  'Receipt total': 'Total del recibo',
  'Original amount': 'Importe original',
  'Actual bank charge': 'Cargo real del banco',
  'Exchange rate': 'Tipo de cambio',
  'Manual rate': 'Tipo de cambio manual',
  'Check rate': 'Revisar cambio',
  'Check & save': 'Revisar y guardar',
  'Check &amp; save': 'Revisar y guardar',
  'Confirm & save expense': 'Confirmar y guardar gasto',
  'Confirm &amp; save expense': 'Confirmar y guardar gasto',
  'Details & split': 'Detalles y reparto',
  'Back to details & split': 'Volver a detalles y reparto',
  Split: 'Reparto',
  Equal: 'Igual',
  Percentages: 'Porcentajes',
  Units: 'Unidades',
  Quantity: 'Cantidad',
  Item: 'Artículo',
  'Item name': 'Nombre del artículo',
  Price: 'Precio',
  Subtotal: 'Subtotal',
  Tax: 'Impuesto',
  Tip: 'Propina',
  Discount: 'Descuento',
  Total: 'Total',
  Notes: 'Notas',
  Note: 'Nota',
  Location: 'Lugar',
  Place: 'Lugar',
  Optional: 'Opcional',
  '(optional)': '(opcional)',
  'Remove receipt photo': 'Quitar foto del recibo',
  'Choose an icon': 'Elige un icono',
  Icon: 'Icono',
  Automatic: 'Automático',
  'Automatic detection': 'Detección automática',
  Check: 'Revisar',
  Payment: 'Pago',
  Payments: 'Pagos',
  'Record paid': 'Registrar pago',
  'Record payment': 'Registrar pago',
  From: 'De',
  To: 'Para',
  Method: 'Método',
  Reference: 'Referencia',
  'Payment details': 'Datos de pago',
  'Bank details (optional)': 'Datos bancarios (opcional)',
  'Bank details:': 'Datos bancarios:',
  'Bank transfer, cash…': 'Transferencia, efectivo…',
  'Copy amount and reference': 'Copiar importe y referencia',
  Remind: 'Recordar',
  'All square': 'Todo saldado',
  Balance: 'Saldo',
  'Before this payment:': 'Antes de este pago:',
  'Suggested transfers': 'Transferencias sugeridas',
  'Paid upfront': 'Pagado por adelantado',
  'Cost share': 'Parte del gasto',
  'Holiday details': 'Detalles del viaje',
  'Holiday name': 'Nombre del viaje',
  'Settlement currency': 'Moneda de liquidación',
  'Start date': 'Fecha de inicio',
  'End date': 'Fecha de fin',
  Budget: 'Presupuesto',
  'Holiday budget': 'Presupuesto del viaje',
  'Group budget': 'Presupuesto del grupo',
  'Budget used': 'Presupuesto utilizado',
  Remaining: 'Restante',
  'Spent so far': 'Gastado hasta ahora',
  'Daily average': 'Media diaria',
  'Trip summary': 'Resumen del viaje',
  'Holiday summary': 'Resumen del viaje',
  'End-of-trip summary': 'Resumen final del viaje',
  'Average per traveller': 'Media por viajero',
  'Final transfers': 'Transferencias finales',
  'Archive for me': 'Archivar para mí',
  'Leave holiday': 'Salir del viaje',
  'Transfer ownership': 'Transferir la propiedad',
  'Choose a connected traveller': 'Elige un viajero con cuenta',
  'Delete holiday': 'Eliminar viaje',
  'Manage holiday': 'Administrar viaje',
  'Holiday management': 'Administrar viaje',
  'Restore holiday': 'Restaurar viaje',
  'Joined on': 'Se incorporó el',
  'Left on': 'Se fue el',
  'Counts as': 'Cuenta como',
  'Traveller options': 'Opciones del viajero',
  'Remove traveller': 'Quitar viajero',
  Invite: 'Invitar',
  'Invite traveller': 'Invitar viajero',
  'Active invitations': 'Invitaciones activas',
  'Invite link': 'Enlace de invitación',
  'Copy link': 'Copiar enlace',
  Copied: 'Copiado',
  'Offline expense capture': 'Capturar gastos sin conexión',
  'Enable on this device': 'Activar en este dispositivo',
  'Disable on this device': 'Desactivar en este dispositivo',
  'Open capture form': 'Abrir formulario de captura',
  'Sync pending expenses': 'Sincronizar gastos pendientes',
  'Review pending entries': 'Revisar entradas pendientes',
  'Review holiday': 'Revisar viaje',
  'Edit pending': 'Editar pendiente',
  'Edit pending expense': 'Editar gasto pendiente',
  'Keep receipt photo': 'Conservar foto del recibo',
  'I checked the converted amount.': 'He revisado el importe convertido.',
  'A photo was shared with TripTab': 'Se ha compartido una foto con TripTab',
  'Attach to this holiday': 'Adjuntar a este viaje',
  'Discard photo': 'Descartar foto',
  'Notification preferences': 'Preferencias de notificación',
  Notifications: 'Notificaciones',
  'Browser notifications': 'Notificaciones del navegador',
  'Allow settlement reminders': 'Permitir recordatorios de pago',
  'Only expenses I’m involved in': 'Solo gastos en los que participo',
  'Daily summary': 'Resumen diario',
  'As activity happens': 'Al momento',
  'In-app only': 'Solo dentro de la aplicación',
  'No notifications': 'Sin notificaciones',
  'Save preferences': 'Guardar preferencias',
  'Current browser': 'Navegador actual',
  Revoke: 'Revocar',
  'Sign out this browser': 'Cerrar esta sesión',
  'Repeat expense': 'Repetir gasto',
  'REPEAT EXPENSE': 'REPETIR GASTO',
  'How long': 'Durante cuánto tiempo',
  'Until a date': 'Hasta una fecha',
  'A number of times': 'Un número de veces',
  'Last date': 'Última fecha',
  'Number of copies': 'Número de copias',
  Every: 'Cada',
  day: 'día',
  '2 days': '2 días',
  week: 'semana',
  'A NEW ADVENTURE': 'UNA NUEVA AVENTURA',
  'HOLIDAY LEDGER': 'CUENTAS DEL VIAJE',
  'Your expenses': 'Tus gastos',
  'About TripTab': 'Acerca de TripTab',
  Help: 'Ayuda',
  Settings: 'Ajustes',
  General: 'General',
  Language: 'Idioma',
  'Interface language': 'Idioma de la interfaz',
  English: 'Inglés',
  Spanish: 'Español',
  Appearance: 'Apariencia',
  Dark: 'Oscuro',
  Light: 'Claro',
  System: 'Sistema',
  'Before:': 'Antes:',
  'After:': 'Después:',
  'Changed by': 'Modificado por',
  Changes: 'Cambios',
  'Restore from history': 'Restaurar desde el historial',
  'Data export': 'Exportar datos',
  'Export holiday': 'Exportar viaje',
  'Financial CSV': 'CSV financiero',
  'Download CSV': 'Descargar CSV',
  'Download receipt': 'Descargar recibo',
  'View photo': 'Ver foto',
  'Show more': 'Mostrar más',
  'Show less': 'Mostrar menos',
  'Show details': 'Mostrar detalles',
  'Hide details': 'Ocultar detalles',
  Expand: 'Expandir',
  Collapse: 'Contraer',
  'Check it. Split it.': 'Revísalo. Repártelo.',
  'A shared dinner doesn’t have to mean an equal bill.':
    'Una cena compartida no exige repartir la cuenta a partes iguales.',
  'ChatGPT connected': 'ChatGPT conectado',
  'ChatGPT plan': 'Plan de ChatGPT',
  'Connect ChatGPT': 'Conectar ChatGPT',
  'Disconnect ChatGPT': 'Desconectar ChatGPT',
  'Add notes first': 'Añadir notas primero',
  'Ask your assistant to itemise it':
    'Pide al asistente que detalle los artículos',
  Processing: 'Procesando',
  Saved: 'Guardado',
  Manual: 'Manual',
  Search: 'Buscar',
  Send: 'Enviar',
  Reply: 'Responder',
  Replies: 'Respuestas',
  Details: 'Detalles',
  Change: 'Cambiar',
  'Change reference': 'Cambiar referencia',
  Allocated: 'Repartido',
  'Your share': 'Tu parte',
  People: 'Personas',
};
