import { readFileSync, writeFileSync } from 'node:fs';
import { createSourceFile, forEachChild, isStringLiteral, ScriptTarget } from 'typescript';
import { getUiCatalog } from '../lib/ui-language';

// The public capture page uses the same reviewed translations as the app.
// Only its public copy is bundled here; no account data is cached.
const keys = new Set<string>(['legacy receipts']);
const html = readFileSync(new URL('../public/offline.html', import.meta.url), 'utf8');
for (const match of html.matchAll(/data-ui="([^"]+)"/g)) keys.add(match[1]);
for (const name of ['offline-capture.js', 'offline-store.js']) {
  const source = createSourceFile(name, readFileSync(new URL(`../public/${name}`, import.meta.url), 'utf8'), ScriptTarget.Latest, true);
  const visit = (node: import('typescript').Node) => {
    if (isStringLiteral(node) && Object.hasOwn(getUiCatalog('es'), node.text)) keys.add(node.text);
    forEachChild(node, visit);
  };
  visit(source);
}
const catalogs = Object.fromEntries(['es', 'fr', 'de'].map(value => {
  const catalog = getUiCatalog(value as 'es' | 'fr' | 'de');
  for (const key of keys) if (!catalog[key]) throw Error(`Missing ${value} offline translation: ${key}`);
  return [value, Object.fromEntries([...keys].sort().map(key => [key, catalog[key]]))];
}));
const output = `/* Generated by scripts/build-offline-language.ts. */
(() => {
  'use strict';
  const catalogs = ${JSON.stringify(catalogs)};
  let language = 'en';
  try { const saved = localStorage.getItem('triptab.ui-language'); if (['en', 'es', 'fr', 'de'].includes(saved)) language = saved; } catch {}
  const t = (text, values = {}) => {
    const core = text.trim(), catalog = catalogs[language] || {}, translated = Object.hasOwn(catalog, core) ? catalog[core] : core;
    return (core ? text.replace(core, translated) : text).replace(/\\{([\\w]+)\\}/g, (placeholder, key) => Object.hasOwn(values, key) ? String(values[key]) : placeholder);
  };
  document.documentElement.lang = language;
  for (const element of document.querySelectorAll('[data-ui]')) element.textContent = t(element.dataset.ui);
  const currencyName = (code, original) => {
    if (language === 'en') return original;
    const name = new Intl.DisplayNames(language, { type: 'currency' }).of(code) || original;
    return original.includes('(legacy receipts)') ? name + ' (' + t('legacy receipts') + ')' : name;
  };
  globalThis.TripTabUi = { t, currencyName, language, locale: language === 'en' ? 'en-GB' : language };
})();
`;
writeFileSync(new URL('../public/offline-language.js', import.meta.url), output);
